### ISSUE TITLE
DonwloadFile returns No resource exception for an existing file

### ISSUE THREAD

**Issue by SensouShin** [gpailler/MegaApiClient#195] opened 2021-11-22 07:51 UTC
In my previous [issue](https://github.com/gpailler/MegaApiClient/issues/192)  i found a bug with getting  a node without file attributes which is  now working in 1.10.1.  There is still an issue with DownloadFile which is throwing a resource not found exception for an existing file. I think this is somehow a related issue for a file without fileattributes.

Call stack
>	MegaApiClient.dll!CG.Web.MegaApiClient.MegaApiClient.RequestCore<CG.Web.MegaApiClient.Serialization.DownloadUrlResponse>(CG.Web.MegaApiClient.Serialization.RequestBase request, byte[] key) Line 1136	C#
 	MegaApiClient.dll!CG.Web.MegaApiClient.MegaApiClient.Request<CG.Web.MegaApiClient.Serialization.DownloadUrlResponse>(CG.Web.MegaApiClient.Serialization.RequestBase request, byte[] key) Line 1092	C#
 	MegaApiClient.dll!CG.Web.MegaApiClient.MegaApiClient.Download(CG.Web.MegaApiClient.INode node, System.Threading.CancellationToken? cancellationToken) Line 600	C#
 	MegaApiClient.dll!CG.Web.MegaApiClient.MegaApiClient.DownloadFile(CG.Web.MegaApiClient.INode node, string outputFile, System.Threading.CancellationToken? cancellationToken) Line 534	C#

MegaApiClient Version:
1.10.1

**Comment by gpailler** [comment] 2021-11-22 08:06
Hello,
Oh right, I didn't check if the Download operation was working for a node without file attributes. I will take a look.

**Comment by SensouShin** [comment] 2021-11-22 08:11
Hello, thanks for the fast reply. I think the bug is somewhere in the request buecase the response just a single int wich is -9.

**Comment by gpailler** [comment] 2021-11-22 09:09
@SensouShin The issue is reproducible with the snippet you provided in #192  ?

**Comment by SensouShin** [comment] 2021-11-22 09:13
> @SensouShin The issue is reproducible with the snippet you provided in #192 ?

Yes.

**Comment by gpailler** [comment] 2021-11-24 05:56
Fixed in 1.10.2

**Closed by gpailler** 2021-11-24 05:56 UTC
