### ISSUE TITLE
Unable to GetNodes (API update?)

### ISSUE THREAD

**Issue by igorquintaes** [gpailler/MegaApiClient#211] opened 2022-09-07 15:40 UTC
**Description**:

Unable to use a simple `client.GetNodes()`. It worked fine one week ago for last year and even more.

**Actual Behavior**:

Client is logged in. When we try to GetNodes(), it throws an exception.

**Expected Behavior**:

Return nodes.

**Steps to reproduce**:

```cs
var user = "";
var pass = "";
var client = new MegaApiClient();
client.Login(user, pass);
if (!client.IsLoggedIn)
    throw new Exception("login error");

var nodes = client.GetNodes(); // Exception here!
```

**Exception details**:

```
Newtonsoft.Json.JsonReaderException
  HResult=0x80131500
  Message=Unexpected character encountered while parsing value: . Path '', line 0, position 0.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at CG.Web.MegaApiClient.MegaApiClient.RequestCore[TResponse](RequestBase request, Byte[] key)
   at CG.Web.MegaApiClient.MegaApiClient.Request[TResponse](RequestBase request, Byte[] key)
   at CG.Web.MegaApiClient.MegaApiClient.GetNodes()
   at ConsoleApp5.Program.Main(String[] args) in C:\Users\Striter\source\repos\ConsoleApp5\ConsoleApp5\Program.cs:line 18

  Esta exceção foi gerada originalmente nesta pilha de chamadas:
    Newtonsoft.Json.JsonTextReader.ParseValue()
    Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
    Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(Newtonsoft.Json.JsonReader, Newtonsoft.Json.Serialization.JsonContract, bool)
    Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(Newtonsoft.Json.JsonReader, System.Type, bool)
    Newtonsoft.Json.JsonSerializer.DeserializeInternal(Newtonsoft.Json.JsonReader, System.Type)
    Newtonsoft.Json.JsonSerializer.Deserialize(Newtonsoft.Json.JsonReader, System.Type)
    Newtonsoft.Json.JsonConvert.DeserializeObject(string, System.Type, Newtonsoft.Json.JsonSerializerSettings)
    CG.Web.MegaApiClient.MegaApiClient.RequestCore<TResponse>(CG.Web.MegaApiClient.Serialization.RequestBase, byte[])
    CG.Web.MegaApiClient.MegaApiClient.Request<TResponse>(CG.Web.MegaApiClient.Serialization.RequestBase, byte[])
    CG.Web.MegaApiClient.MegaApiClient.GetNodes()
```

**MegaApiClient Version**: latest

**Comment by gpailler** [comment] 2022-09-11 02:23
Hello,

Could you take a look on #74 and check if it's the same root cause (a folder or file marked as "encrypted" on your Mega account)

Thanks

**Comment by igorquintaes** [comment] 2022-09-11 13:20
Hello, @gpailler 

I just had a look into the mega account and I couldn't find anything strange in files and folders - there is also none folder shared with the account. I also tried running [MegaDebug.zip](https://github.com/gpailler/MegaApiClient/files/1336251/MegaDebug.zip), but it threw me a similar error:

> Unexpected character encountered while parsing value: ▼. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   at CG.Web.MegaApiClient.MegaApiClient.RequestCore[TResponse](RequestBase request, Byte[] key) in C:\Users\gpailler\Documents\Repos\GitHub\MegaApiClient\MegaApiClient\MegaApiClient.cs:line 1001
   at CG.Web.MegaApiClient.MegaApiClient.Request[TResponse](RequestBase request, Byte[] key) in C:\Users\gpailler\Documents\Repos\GitHub\MegaApiClient\MegaApiClient\MegaApiClient.cs:line 980
   at CG.Web.MegaApiClient.MegaApiClient.GetNodes() in C:\Users\gpailler\Documents\Repos\GitHub\MegaApiClient\MegaApiClient\MegaApiClient.cs:line 272
   at MegaDebug.Program.Main(String[] args)
Done

Last year, just my personal program accessed that account. It only lists nodes and creates folders/files. My mega account has 77% free storage space, but 978 files and 129 folders. 

![image](https://user-images.githubusercontent.com/10831729/189529697-d74dbb0b-3a06-459c-8c17-7029d019c86c.png)

I am going to clone this repo and debug it in order to find some readable Mega's reponse from its API

**Comment by igorquintaes** [comment] 2022-09-11 14:03
Ok, I found the problem. I think due to the large amount of files and folders in my Mega account, it is sending a compressed response. I could handle it in a simple way, just need to add `AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate` in HttpClientHandler. I don't know what approach you prefer to use (to ask for na uncompressed result or handle it). because that, I didn't open correction PR.

**Comment by gpailler** [comment] 2022-09-12 00:11
Thanks for your investigation.
I don't think that there is any drawback to set `AutomaticDecompression` to `DecompressionMethods.GZip | DecompressionMethods.Deflate` all the time. Could you share a PR then we will see if all the tests pass?

Thanks

**Closed** 2022-10-02 02:44 UTC
