### ISSUE TITLE
Upload use too much processor time

### ISSUE THREAD

**Issue by helpme1c** [gpailler/MegaApiClient#70] opened 2017-09-07 01:18 UTC
**Description**:
*what are you trying to do*
I use MegaApiClient in my program for upload file to mega.nz.
**Actual Behavior**:
*what happens*
Program use ~20% processor time on upload file.
**Expected Behavior**:
*what should happen* 
Other libs (e.g. google drive c# lib) use only 1-3% for this operation.
**MegaApiClient Version**: 1.6.0.0

**Comment by gpailler** [comment] 2017-09-07 03:52
One of the main difference between GDrive and Mega is data is encrypted on client side.
But there is probably room for improvement. 

CPU usage is related to #66.

**Comment by helpme1c** [comment] 2017-09-07 03:59
Thanks for your answer. I thought as much.

**Comment by helpme1c** [comment] 2017-09-07 07:40
By the way Chrome on uploading (with encrypt) to mega.nz use only 5% processor time.

**Comment by gpailler** [comment] 2017-09-08 05:00
Related to #66

**Comment by gpailler** [comment] 2017-09-08 05:02
Duplicate of #66

**Closed** 2017-09-08 05:03 UTC
Labels: duplicate
