### ISSUE TITLE
Upload stopped working - hangs forevers

### ISSUE THREAD

**Issue by dgenezini** [gpailler/MegaApiClient#100] opened 2018-07-22 11:45 UTC
**Description**: 

Trying to upload a 500KB file.

**Actual Behavior**:

Upload hangs forever and shows no error.

**Expected Behavior**:

Upload completes.

**Steps to Reproduce**:

```
            var client = new MegaApiClient();
            client.Login("email", "password");

            IEnumerable<INode> nodes = client.GetNodes();

            INode root = nodes.Single(x => x.Type == NodeType.Root);

            INode controleAtual = nodes.SingleOrDefault(x => x.Name == "controle.db");

            if (controleAtual != null)
            {
                client.Rename(controleAtual, $"controle_{DateTime.Now.ToString("yyyyMMddHHmmss")}.db");
            }

            INode myFile = client.UploadFile("controle.db", root);

            client.Logout();
```

**MegaApiClient Version**:
Was working on 1.6.2 and stopped, tried on 1.6.3 and same bahaviour.

**Comment by gpailler** [comment] 2018-07-23 21:06
I reproduce the issue. It seems something has changed on Mega side about the completion handle.
I'm investigating

**Comment by Grizzan** [comment] 2018-07-27 00:35
It looks like fixed by themself today. We got this problem for 2 week.

**Comment by gpailler** [comment] 2018-07-28 13:44
It was probably an issue on Mega side but I was not able to find any details

**Closed by gpailler** 2018-07-28 13:44 UTC
Labels: bug
