### ISSUE TITLE
Upload hangs in HttpClient.PostRequest

### ISSUE THREAD

**Issue by Parasite03** [gpailler/MegaApiClient#147] opened 2020-05-24 21:21 UTC
**Description**:

I'm mass-uploading small files. It works well for about 500-600 of them, but then the program just hangs.

**Actual Behavior**:

 Turns out that in HttpCLient.Post request at
`HttpResponseMessage response = this.httpClient.PostAsync(url, content).Result`
it just hangs. The response doesn't come

**Expected Behavior**:

The program works fine and keeps uploading files.

**MegaApiClient Version**: 1.8.1

**Comment by gpailler** [comment] 2020-05-25 13:22
Hi @Parasite03 . I also notice this kind of random hang when running the unit tests. Are you using a free or a pro account?

**Comment by Parasite03** [comment] 2020-05-25 13:26
@gpailler Free 50 GB account. DO you think that could be the issue? I recently had it happen on like the 10th upload though.

**Comment by gpailler** [comment] 2020-05-25 13:42
I don't have any explanation for this issue for now. Sometimes, it just hangs indefinitely, without any response from the mega servers. I'm wondering if it's not a kind of API/Upload throttling... And each time I decide to spend some time to investigate, it works just fine 😒...
I'm wondering if someone with a pro account experiences the same kind of hang

**Comment by Parasite03** [comment] 2020-05-25 14:42
Hm... I have them happening reliably, just not with a reliable rate (sometimes earler, other times later). I could mby set you up with my program? Also I have some suspicious that PC resource availability might have something to do with it, but it's just a guess and may be wrong.

**Comment by gpailler** [comment] 2020-05-25 15:12
Sure, If you are willing to share a sample app to reproduce the problem, I'm interested to investigate deeper.

**Comment by Parasite03** [comment] 2020-05-25 15:43
Okay, so I stripped my program down as to not make you deal with random stuff and I was able to cause it to hang. it actually happened quite fast.
Don't forget to put your credentials in in SmtpHandler.cs

So steps to reproduce:
1. Load PDF
2. Load Excel
3. Generate Certificates (it'll spam a bunch of PDFs into the folder you select)
4. Load another PDF, repeat
5. Email settings -> Save (don't need to change anything)
6. Send emails (won't actually send anything, just upload a bunch of them into a folder on Mega)

I've included a couple sample pdfs and an excel file to load you can use.
It's too big, so here's a link:
https://yadi.sk/d/KGKtJ-GYvKFTlA

**Comment by gpailler** [comment] 2020-05-26 14:45
Thanks for the sample. I will try to reproduce and I will keep you posted

**Comment by Parasite03** [comment] 2020-05-26 14:49
Actually, I might have something. I tried setting the timeout to a finite number (100000) and it never hangds now. However, it also never throws and exception and I haven't seen a file that wasn't uploaded yet (although I may be mistaken).

**Comment by Parasite03** [comment] 2020-05-26 16:53
Okay, nevermind the last comment. It does make it work but only because you have a loop set up that retries it over and over until it eventually succeeds. Takes forever, though.

**Comment by Parasite03** [comment] 2020-05-26 17:48
Okay, now I get a ResourceNotExists every now and then....

**Comment by gpailler** [comment] 2020-05-27 16:18
I'm able to reproduce with your app. I will try to fix it and keep you posted. Thanks

**Comment by Parasite03** [comment] 2020-05-30 09:56
I had to buy a paid plan and now I don't seem to get the error anymore. Interesting.

**Comment by gpailler** [comment] 2020-05-31 12:35
On my side, I tried several times this weekend but I'm not able to reproduce again. Still trying...

**Comment by gpailler** [comment] 2020-06-06 07:14
@Parasite03, By any chance, could you try the nuget package from https://ci.appveyor.com/project/gpailler/megaapiclient/builds/33353633/artifacts ? I fixed an issue when PostRequest hangs when the mega servers return a 500 error. 
I tested by uploading thousands of files for more than 24h and it seems fixed but I would like your confirmation.

**Comment by gpailler** [comment] 2020-08-16 12:25
Issue fixed on 1.8.2

**Closed by gpailler** 2020-08-16 12:25 UTC
Labels: bug
